//File: TestO.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--29:
//function y=TestO(x) 

//% This example uses MultRoot by ZHONGGANG ZENG

//% References:

//% [1] ZHONGGANG ZENG, "COMPUTING MULTIPLE ROOTS OF INEXACT POLYNOMIALS",

//% MATHEMATICS OF COMPUTATION,

//% Volume 74, Number 250, Pages 869-903

//% S 0025-5718(04)01692-8

//% Article electronically published on July 22, 2004

//% [2] ZHONGGANG ZENG, "MultRoot - A Matlab package computing polynomial roots and multiplicities"

//% Journal ACM Transactions on Mathematical Software (TOMS), Volume 30 Issue 2, June 2004 , Pages 218-236

//

//

//

//% www=load('D:\Data_D\HSKOST\TMC\qd_tmc\tmc_src-1.02\examples\AppEx_qd\testroot1.mat')

//%figure(222);plot( real(www.xx),imag(www.xx),'r.',real(www.qxx),imag(www.qxx),'bo',real(roots(www.aa)),imag(roots(www.aa)),'gx');grid on;

//% www=load('HH.mat');

//% A=www.HH;

//% B=www.B;

//% disp(det(A));

//% disp(det_qd(A));

//% disp(eig(A));

//% disp(eig_qd(A));

//%disp(A\B);

//%  disp(leftdivide_qd(A,B));

//% return

//

//

//

//ar = 0.00001;

void tmcTestO(int nargout, int nargin,tmsMatrix *y
,tmsMatrix *x) {
tmsMatrix **reg=tmcCreateRegFrame(134);
tmsMatrix *ar=tmcNewMatrix();
tmsMatrix *ai=tmcNewMatrix();
tmsMatrix *x0=tmcNewMatrix();
tmsMatrix *x1=tmcNewMatrix();
tmsMatrix *va=tmcNewMatrix();
tmsMatrix *vb=tmcNewMatrix();
tmsMatrix *aa=tmcNewMatrix();
tmsMatrix *xx=tmcNewMatrix();
tmsMatrix *qxx=tmcNewMatrix();
tmsMatrix *cnt=tmcNewMatrix();
tmsMatrix *yy=tmcNewMatrix();
tmsMatrix *qyy=tmcNewMatrix();
tmsMatrix *qerr=tmcNewMatrix();
tmsMatrix *mqq=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",16,
x,"x",
y,"y",
ar,"ar",
ai,"ai",
x0,"x0",
x1,"x1",
va,"va",
vb,"vb",
aa,"aa",
xx,"xx",
qxx,"qxx",
cnt,"cnt",
yy,"yy",
qyy,"qyy",
qerr,"qerr",
mqq,"mqq");

tmcScalar(reg[1],1.000000000000000e-005);

tmcAssign(ar,reg[1]);
//statement here,line 29

// % Lines 30--30:
//ai  = 10;

tmcScalar(reg[3],1.000000000000000e+001);

tmcAssign(ai,reg[3]);
//statement here,line 30

// % Lines 31--32:
//

//x0 = ar + ai*j;



//CALL function
tmcReallocRegister(reg[7]);
tmcj(1,0, reg[7]);
tmcMul(reg[8],ai,reg[7]);
tmcAdd(reg[9],ar,reg[8]);

tmcAssign(x0,reg[9]);
//statement here,line 32

// % Lines 33--33:
//x1 = ar - ai*j;



//CALL function
tmcReallocRegister(reg[13]);
tmcj(1,0, reg[13]);
tmcMul(reg[14],ai,reg[13]);
tmcSub(reg[15],ar,reg[14]);

tmcAssign(x1,reg[15]);
//statement here,line 33

// % Lines 34--35:
//

//va = [1, -2*ar,ar^2+ai^2];

tmcScalar(reg[17],1.000000000000000e+000);
tmcScalar(reg[18],2.000000000000000e+000);
tmcNeg(reg[19],reg[18]);

tmcMul(reg[21],reg[19],ar);

tmcScalar(reg[23],2.000000000000000e+000);
tmcPower(reg[24],ar,reg[23]);

tmcScalar(reg[26],2.000000000000000e+000);
tmcPower(reg[27],ai,reg[26]);
tmcAdd(reg[28],reg[24],reg[27]);
tmcCollectColumns(reg[29],3,reg[17],reg[21],reg[28]);
tmcCollectRows(reg[30],1,reg[29]);

tmcAssign(va,reg[30]);
//statement here,line 35

// % Lines 36--36:
//vb = va;



tmcAssign(vb,va);
//statement here,line 36

// % Lines 37--37:
//vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[36]);
tmcconv(1,2, reg[36], vb, va);

tmcAssign(vb,reg[36]);
//statement here,line 37

// % Lines 38--38:
//vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[40]);
tmcconv(1,2, reg[40], vb, va);

tmcAssign(vb,reg[40]);
//statement here,line 38

// % Lines 39--39:
//vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[44]);
tmcconv(1,2, reg[44], vb, va);

tmcAssign(vb,reg[44]);
//statement here,line 39

// % Lines 40--40:
// vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[48]);
tmcconv(1,2, reg[48], vb, va);

tmcAssign(vb,reg[48]);
//statement here,line 40

// % Lines 41--41:
// vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[52]);
tmcconv(1,2, reg[52], vb, va);

tmcAssign(vb,reg[52]);
//statement here,line 41

// % Lines 42--42:
// vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[56]);
tmcconv(1,2, reg[56], vb, va);

tmcAssign(vb,reg[56]);
//statement here,line 42

// % Lines 43--43:
// vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[60]);
tmcconv(1,2, reg[60], vb, va);

tmcAssign(vb,reg[60]);
//statement here,line 43

// % Lines 44--44:
// vb = conv(vb,va);



//CALL function
tmcReallocRegister(reg[64]);
tmcconv(1,2, reg[64], vb, va);

tmcAssign(vb,reg[64]);
//statement here,line 44

// % Lines 45--55:
// 

//%   vb = conv(vb,va);

//%  vb = conv(vb,va);

//%  vb = conv(vb,va);

//

//% aa=[1,909,367236,86545284,13111610526,1324272663126,...

//%         89167692650484,3859687267585236,97457103506527209,1093685272684360901];

//

//

//

//aa = vb;



tmcAssign(aa,vb);
//statement here,line 55

// % Lines 56--56:
//xx =  roots( aa);


//CALL function
tmcReallocRegister(reg[69]);
tmcroots(1,1, reg[69], aa);

tmcAssign(xx,reg[69]);
//statement here,line 56

// % Lines 57--57:
//qxx =  roots_qd( aa);


//CALL function
tmcReallocRegister(reg[72]);
tmcroots_qd(1,1, reg[72], aa);

tmcAssign(qxx,reg[72]);
//statement here,line 57

// % Lines 58--59:
//

//disp('Roots=');

tmcCreateString(reg[74],"Roots=");
//CALL function
tmcReallocRegister(reg[75]);
tmcdisp(0,1, reg[75], reg[74]);
//statement here,line 59

// % Lines 60--60:
//disp(xx);


//CALL function
tmcReallocRegister(reg[77]);
tmcdisp(0,1, reg[77], xx);
//statement here,line 60

// % Lines 61--62:
//for cnt=1:length(xx)

//    yy(cnt) = polyval(aa,xx(cnt));    

tmcScalar(reg[78],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[80]);
tmclength(1,1, reg[80], xx);
tmcCreateColonBaseLimit(reg[81],reg[78],reg[80]);
tmcForIterInit(reg[82],reg[81],cnt);
label_4: ; //FOR begin
if(tmcForIterNext(reg[82],reg[81])) goto label_3; // exit for



tmcGetByIndex(reg[86],xx,1,cnt);
//CALL function
tmcReallocRegister(reg[87]);
tmcpolyval(1,2, reg[87], aa, reg[86]);


tmcGetRefByIndex(pRefHelper,yy,1,cnt);
tmcAssign(pRefHelper,reg[87]);
//statement here,line 62

// % Lines 63--63:
//end

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 63

// % Lines 64--64:
//disp('P(roots)=');

tmcCreateString(reg[90],"P(roots)=");
//CALL function
tmcReallocRegister(reg[91]);
tmcdisp(0,1, reg[91], reg[90]);
//statement here,line 64

// % Lines 65--65:
//disp(yy);


//CALL function
tmcReallocRegister(reg[93]);
tmcdisp(0,1, reg[93], yy);
//statement here,line 65

// % Lines 66--69:
//

//

//

//disp('Quad Roots=');

tmcCreateString(reg[94],"Quad Roots=");
//CALL function
tmcReallocRegister(reg[95]);
tmcdisp(0,1, reg[95], reg[94]);
//statement here,line 69

// % Lines 70--70:
//disp(qxx);


//CALL function
tmcReallocRegister(reg[97]);
tmcdisp(0,1, reg[97], qxx);
//statement here,line 70

// % Lines 71--72:
//for cnt=1:length(qxx)

//    qyy(cnt) = polyval(aa,qxx(cnt));    

tmcScalar(reg[98],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[100]);
tmclength(1,1, reg[100], qxx);
tmcCreateColonBaseLimit(reg[101],reg[98],reg[100]);
tmcForIterInit(reg[102],reg[101],cnt);
label_7: ; //FOR begin
if(tmcForIterNext(reg[102],reg[101])) goto label_6; // exit for



tmcGetByIndex(reg[106],qxx,1,cnt);
//CALL function
tmcReallocRegister(reg[107]);
tmcpolyval(1,2, reg[107], aa, reg[106]);


tmcGetRefByIndex(pRefHelper,qyy,1,cnt);
tmcAssign(pRefHelper,reg[107]);
//statement here,line 72

// % Lines 73--73:
//end

label_5: ; //FOR end
goto label_7; //branch to FOR begin
label_6: ; //FOR exit
//statement here,line 73

// % Lines 74--76:
//

//

//disp('***********************************************');

tmcCreateString(reg[110],"***********************************************");
//CALL function
tmcReallocRegister(reg[111]);
tmcdisp(0,1, reg[111], reg[110]);
//statement here,line 76

// % Lines 77--77:
//disp('Quad P(roots)=');

tmcCreateString(reg[112],"Quad P(roots)=");
//CALL function
tmcReallocRegister(reg[113]);
tmcdisp(0,1, reg[113], reg[112]);
//statement here,line 77

// % Lines 78--78:
//disp(qyy);


//CALL function
tmcReallocRegister(reg[115]);
tmcdisp(0,1, reg[115], qyy);
//statement here,line 78

// % Lines 79--79:
//qerr = qxx - xx;



tmcSub(reg[118],qxx,xx);

tmcAssign(qerr,reg[118]);
//statement here,line 79

// % Lines 80--80:
//disp(qerr);


//CALL function
tmcReallocRegister(reg[121]);
tmcdisp(0,1, reg[121], qerr);
//statement here,line 80

// % Lines 81--82:
//

//disp('Coeficcients: aa=');

tmcCreateString(reg[122],"Coeficcients: aa=");
//CALL function
tmcReallocRegister(reg[123]);
tmcdisp(0,1, reg[123], reg[122]);
//statement here,line 82

// % Lines 83--83:
//disp(aa);


//CALL function
tmcReallocRegister(reg[125]);
tmcdisp(0,1, reg[125], aa);
//statement here,line 83

// % Lines 84--85:
//

//mqq = multroot(aa);


//CALL function
tmcReallocRegister(reg[127]);
tmcmultroot(1,1, reg[127], aa,NULL);

tmcAssign(mqq,reg[127]);
//statement here,line 85

// % Lines 86--86:
//disp('multroots=');

tmcCreateString(reg[129],"multroots=");
//CALL function
tmcReallocRegister(reg[130]);
tmcdisp(0,1, reg[130], reg[129]);
//statement here,line 86

// % Lines 87--87:
//disp(mqq);


//CALL function
tmcReallocRegister(reg[132]);
tmcdisp(0,1, reg[132], mqq);
//statement here,line 87

// % Lines 88--89:
//

//save('testroot1.mat','aa','xx','qxx','yy','qyy','x0');

tmcCreateString(reg[133],"testroot1.mat");
//CALL function save
tmcsave(0,7, reg[133], aa, "aa", xx, "xx", qxx, "qxx", yy, "yy", qyy, "qyy", x0, "x0");
//statement here,line 89

// % Lines 90--93:
//

//

//

// 
label_1: ; //end Function
FINALLY
tmcFreeLocalVar(mqq);
tmcFreeLocalVar(qerr);
tmcFreeLocalVar(qyy);
tmcFreeLocalVar(yy);
tmcFreeLocalVar(cnt);
tmcFreeLocalVar(qxx);
tmcFreeLocalVar(xx);
tmcFreeLocalVar(aa);
tmcFreeLocalVar(vb);
tmcFreeLocalVar(va);
tmcFreeLocalVar(x1);
tmcFreeLocalVar(x0);
tmcFreeLocalVar(ai);
tmcFreeLocalVar(ar);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(16);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 93

// % Lines 94--94:
