//File: TestO.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--4:
//function y=TestO(x) 

//%addpath('D:\Data_D\HSKOST\TMC\TMC_forLibre\examples\AppSIMO\MexSRC\MexDLLS')

//%addpath('D:\Data_D\HSKOST\TMC\TMC_forLibre\examples\AppSIMO\MatSRC')

//global ite;

void tmcTestO(int nargout, int nargin,tmsMatrix *y
,tmsMatrix *x__input__tmc) {
tmsMatrix **reg=tmcCreateRegFrame(184);
tmsMatrix *x=tmcNewMatrix();
tmsMatrix *A=tmcNewMatrix();
tmsMatrix *B=tmcNewMatrix();
tmsMatrix *C=tmcNewMatrix();
tmsMatrix *summa=tmcNewMatrix();
tmsMatrix *S=tmcNewMatrix();
tmsMatrix *K=tmcNewMatrix();
tmsMatrix *a=tmcNewMatrix();
tmsMatrix *b=tmcNewMatrix();
tmsMatrix *Len=tmcNewMatrix();
tmsMatrix *e=tmcNewMatrix();
tmsMatrix *z=tmcNewMatrix();
tmsMatrix *k=tmcNewMatrix();
tmsMatrix *ep1=tmcNewMatrix();

tmcCopyMat(x,x__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("TestO",16,
x__input__tmc,"x__input__tmc",
y,"y",
x,"x",
A,"A",
B,"B",
C,"C",
summa,"summa",
S,"S",
K,"K",
a,"a",
b,"b",
Len,"Len",
e,"e",
z,"z",
k,"k",
ep1,"ep1");

//statement here,line 4

// % Lines 5--5:
//A=[1,2;3,4];

tmcScalar(reg[1],1.000000000000000e+000);
tmcScalar(reg[2],2.000000000000000e+000);
tmcCollectColumns(reg[3],2,reg[1],reg[2]);
tmcScalar(reg[4],3.000000000000000e+000);
tmcScalar(reg[5],4.000000000000000e+000);
tmcCollectColumns(reg[6],2,reg[4],reg[5]);
tmcCollectRows(reg[7],2,reg[3],reg[6]);

tmcAssign(A,reg[7]);
//statement here,line 5

// % Lines 6--6:
//B=[1;3];

tmcScalar(reg[9],1.000000000000000e+000);
tmcCollectColumns(reg[10],1,reg[9]);
tmcScalar(reg[11],3.000000000000000e+000);
tmcCollectColumns(reg[12],1,reg[11]);
tmcCollectRows(reg[13],2,reg[10],reg[12]);

tmcAssign(B,reg[13]);
//statement here,line 6

// % Lines 7--7:
//C =A*B;



tmcMul(reg[17],A,B);

tmcAssign(C,reg[17]);
//statement here,line 7

// % Lines 8--8:
//disp(C\B);



tmcLeftDiv(reg[21],C,B);
//CALL function
tmcReallocRegister(reg[22]);
tmcdisp(0,1, reg[22], reg[21]);
//statement here,line 8

// % Lines 9--9:
//return;

goto label_1; //branch to FUNCTION exit
//statement here,line 9

// % Lines 10--11:
//

//x=[1:100];

tmcScalar(reg[23],1.000000000000000e+000);
tmcScalar(reg[24],1.000000000000000e+002);
tmcCreateColonBaseLimit(reg[25],reg[23],reg[24]);
tmcCollectColumns(reg[26],1,reg[25]);
tmcCollectRows(reg[27],1,reg[26]);

tmcAssign(x,reg[27]);
//statement here,line 11

// % Lines 12--12:
//summa = sum(x);


//CALL function
tmcReallocRegister(reg[30]);
tmcsum(1,1, reg[30], x);

tmcAssign(summa,reg[30]);
//statement here,line 12

// % Lines 13--13:
//disp(summa);


//CALL function
tmcReallocRegister(reg[33]);
tmcdisp(0,1, reg[33], summa);
//statement here,line 13

// % Lines 14--16:
//

//

//x = [1:100];

tmcScalar(reg[34],1.000000000000000e+000);
tmcScalar(reg[35],1.000000000000000e+002);
tmcCreateColonBaseLimit(reg[36],reg[34],reg[35]);
tmcCollectColumns(reg[37],1,reg[36]);
tmcCollectRows(reg[38],1,reg[37]);

tmcAssign(x,reg[38]);
//statement here,line 16

// % Lines 17--17:
//S=cell(2,1);

tmcScalar(reg[40],2.000000000000000e+000);
tmcScalar(reg[41],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[42]);
tmccell(1,2, reg[42], reg[40], reg[41]);

tmcAssign(S,reg[42]);
//statement here,line 17

// % Lines 18--18:
//S{1}.r=x;



tmcScalar(reg[46],1.000000000000000e+000);
tmcGetRefByIndexCell(pRefHelper,S,1,reg[46]);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x00720000);/* r */
tmcAssign(pRefHelper,x);
//statement here,line 18

// % Lines 19--19:
//S{2}.r=x*2;


tmcScalar(reg[49],2.000000000000000e+000);
tmcMul(reg[50],x,reg[49]);

tmcScalar(reg[52],2.000000000000000e+000);
tmcGetRefByIndexCell(pRefHelper,S,1,reg[52]);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x00720000);/* r */
tmcAssign(pRefHelper,reg[50]);
//statement here,line 19

// % Lines 20--20:
//S{end} = 44;

tmcScalar(reg[54],4.400000000000000e+001);

tmcGetEnd(reg[56],S,1,1);
tmcGetRefByIndexCell(pRefHelper,S,1,reg[56]);
tmcAssign(pRefHelper,reg[54]);
//statement here,line 20

// % Lines 21--21:
//disp(['R=',num2str(S{end-1}.r(end-1))]);

tmcCreateString(reg[57],"R=");

tmcGetEnd(reg[59],S,1,1);
tmcScalar(reg[60],1.000000000000000e+000);
tmcSub(reg[61],reg[59],reg[60]);
tmcGetByIndexCell(reg[62],S,1,reg[61]);
tmcGetByFieldHcode(reg[64],reg[62],0x00720000);/* r */
tmcGetEnd(reg[65],reg[64],1,1);
tmcScalar(reg[66],1.000000000000000e+000);
tmcSub(reg[67],reg[65],reg[66]);
tmcGetByIndex(reg[68],reg[64],1,reg[67]);
//CALL function
tmcReallocRegister(reg[69]);
tmcnum2str(1,1, reg[69], reg[68],NULL);
tmcCollectColumns(reg[70],2,reg[57],reg[69]);
tmcCollectRows(reg[71],1,reg[70]);
//CALL function
tmcReallocRegister(reg[72]);
tmcdisp(0,1, reg[72], reg[71]);
//statement here,line 21

// % Lines 22--22:
//disp(S);


//CALL function
tmcReallocRegister(reg[74]);
tmcdisp(0,1, reg[74], S);
//statement here,line 22

// % Lines 23--23:
//K=struct;

//CALL function
tmcReallocRegister(reg[75]);
tmcstruct(1,0, reg[75]);

tmcAssign(K,reg[75]);
//statement here,line 23

// % Lines 24--24:
//K.y=[1:100];

tmcScalar(reg[77],1.000000000000000e+000);
tmcScalar(reg[78],1.000000000000000e+002);
tmcCreateColonBaseLimit(reg[79],reg[77],reg[78]);
tmcCollectColumns(reg[80],1,reg[79]);
tmcCollectRows(reg[81],1,reg[80]);

tmcGetRefByFieldHcode(pRefHelper,K,0x00790000);/* y */
tmcAssign(pRefHelper,reg[81]);
//statement here,line 24

// % Lines 25--25:
//disp(K(end).y(end-3));


tmcGetEnd(reg[85],K,1,1);
tmcGetByIndex(reg[86],K,1,reg[85]);
tmcGetByFieldHcode(reg[88],reg[86],0x00790000);/* y */
tmcGetEnd(reg[89],reg[88],1,1);
tmcScalar(reg[90],3.000000000000000e+000);
tmcSub(reg[91],reg[89],reg[90]);
tmcGetByIndex(reg[92],reg[88],1,reg[91]);
//CALL function
tmcReallocRegister(reg[93]);
tmcdisp(0,1, reg[93], reg[92]);
//statement here,line 25

// % Lines 26--29:
//

//

//

//a = -5;

tmcScalar(reg[94],5.000000000000000e+000);
tmcNeg(reg[95],reg[94]);

tmcAssign(a,reg[95]);
//statement here,line 29

// % Lines 30--30:
//b =  50;

tmcScalar(reg[97],5.000000000000000e+001);

tmcAssign(b,reg[97]);
//statement here,line 30

// % Lines 31--31:
//Len =x;



tmcAssign(Len,x);
//statement here,line 31

// % Lines 32--32:
//e = logspace( -5, -2,Len);

tmcScalar(reg[101],5.000000000000000e+000);
tmcNeg(reg[102],reg[101]);
tmcScalar(reg[103],2.000000000000000e+000);
tmcNeg(reg[104],reg[103]);

//CALL function
tmcReallocRegister(reg[106]);
tmclogspace(1,3, reg[106], reg[102], reg[104], Len);

tmcAssign(e,reg[106]);
//statement here,line 32

// % Lines 33--33:
//e = fliplr(e);


//CALL function
tmcReallocRegister(reg[109]);
tmcfliplr(1,1, reg[109], e);

tmcAssign(e,reg[109]);
//statement here,line 33

// % Lines 34--34:
//y = zeros(1,Len);

tmcScalar(reg[111],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[113]);
tmczeros(1,2, reg[113], reg[111], Len);

tmcAssign(y,reg[113]);
//statement here,line 34

// % Lines 35--35:
//x=y;



tmcAssign(x,y);
//statement here,line 35

// % Lines 36--36:
//z=y;



tmcAssign(z,y);
//statement here,line 36

// % Lines 37--38:
//for k=1:length(e)

//    ep1  = e(k);

tmcScalar(reg[119],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[121]);
tmclength(1,1, reg[121], e);
tmcCreateColonBaseLimit(reg[122],reg[119],reg[121]);
tmcForIterInit(reg[123],reg[122],k);
label_4: ; //FOR begin
if(tmcForIterNext(reg[123],reg[122])) goto label_3; // exit for


tmcGetByIndex(reg[126],e,1,k);

tmcAssign(ep1,reg[126]);
//statement here,line 38

// % Lines 39--39:
//    S=solvemyeq(a,b,ep1);




//CALL function
tmcReallocRegister(reg[131]);
tmcsolvemyeq(1,3, reg[131], a, b, ep1);

tmcAssign(S,reg[131]);
//statement here,line 39

// % Lines 40--41:
//    if ~isempty(S)

//        y(k) = S.y0; x(k) = S.x0;


//CALL function
tmcReallocRegister(reg[134]);
tmcisempty(1,1, reg[134], S);
tmcNot(reg[135],reg[134]);
if(tmcIsFalse(reg[135])) goto label_6; // goto to the end of the clause if the expression is false

tmcGetByFieldHcode(reg[138],S,0x0ed70000);/* y0 */


tmcGetRefByIndex(pRefHelper,y,1,k);
tmcAssign(pRefHelper,reg[138]);
//statement here,line 41


tmcGetByFieldHcode(reg[143],S,0x0eb80000);/* x0 */


tmcGetRefByIndex(pRefHelper,x,1,k);
tmcAssign(pRefHelper,reg[143]);
//statement here,line 41

// % Lines 42--42:
//        z(k) = ite;




tmcGetRefByIndex(pRefHelper,z,1,k);
tmcAssign(pRefHelper,ite);
//statement here,line 42

// % Lines 43--43:
//    end

goto label_5; //branch to end IF
label_6: ; //end IF clause
label_5: ; //end IF
//statement here,line 43

// % Lines 44--44:
//end

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 44

// % Lines 45--45:
//save('res.mat','y','x','z');

tmcCreateString(reg[149],"res.mat");
//CALL function save
tmcsave(0,4, reg[149], y, "y", x, "x", z, "z");
//statement here,line 45

// % Lines 46--49:
//%fp=fopen('res.txt');

//%fprintf(fp,'done Ok');

//%fclose(fp);

//return;

goto label_1; //branch to FUNCTION exit
//statement here,line 49

// % Lines 50--51:
//

//figure(10);

tmcScalar(reg[150],1.000000000000000e+001);
//CALL function
tmcReallocRegister(reg[151]);
tmcfigure(0,1, reg[151], reg[150]);
//statement here,line 51

// % Lines 52--52:
//subplot(3,1,1);

tmcScalar(reg[152],3.000000000000000e+000);
tmcScalar(reg[153],1.000000000000000e+000);
tmcScalar(reg[154],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[155]);
tmcsubplot(0,3, reg[155], reg[152], reg[153], reg[154]);
//statement here,line 52

// % Lines 53--53:
//plot(e,y,'b');grid on;



tmcCreateString(reg[158],"b");
//CALL function
tmcReallocRegister(reg[159]);
tmcplot(0,3, reg[159], e, y, reg[158]);
//statement here,line 53

tmcCreateString(reg[160],"on");
//CALL function
tmcReallocRegister(reg[161]);
tmcgrid(0,1, reg[161], reg[160]);
//statement here,line 53

// % Lines 54--54:
//subplot(3,1,2);

tmcScalar(reg[162],3.000000000000000e+000);
tmcScalar(reg[163],1.000000000000000e+000);
tmcScalar(reg[164],2.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[165]);
tmcsubplot(0,3, reg[165], reg[162], reg[163], reg[164]);
//statement here,line 54

// % Lines 55--55:
//plot(e,x,'r');grid on;



tmcCreateString(reg[168],"r");
//CALL function
tmcReallocRegister(reg[169]);
tmcplot(0,3, reg[169], e, x, reg[168]);
//statement here,line 55

tmcCreateString(reg[170],"on");
//CALL function
tmcReallocRegister(reg[171]);
tmcgrid(0,1, reg[171], reg[170]);
//statement here,line 55

// % Lines 56--56:
//subplot(3,1,3);

tmcScalar(reg[172],3.000000000000000e+000);
tmcScalar(reg[173],1.000000000000000e+000);
tmcScalar(reg[174],3.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[175]);
tmcsubplot(0,3, reg[175], reg[172], reg[173], reg[174]);
//statement here,line 56

// % Lines 57--57:
//plot(e,z,'g');grid on;



tmcCreateString(reg[178],"g");
//CALL function
tmcReallocRegister(reg[179]);
tmcplot(0,3, reg[179], e, z, reg[178]);
//statement here,line 57

tmcCreateString(reg[180],"on");
//CALL function
tmcReallocRegister(reg[181]);
tmcgrid(0,1, reg[181], reg[180]);
//statement here,line 57

// % Lines 58--59:
//

//disp('done');

tmcCreateString(reg[182],"done");
//CALL function
tmcReallocRegister(reg[183]);
tmcdisp(0,1, reg[183], reg[182]);
//statement here,line 59

// % Lines 60--61:
//

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(ep1);
tmcFreeLocalVar(k);
tmcFreeLocalVar(z);
tmcFreeLocalVar(e);
tmcFreeLocalVar(Len);
tmcFreeLocalVar(b);
tmcFreeLocalVar(a);
tmcFreeLocalVar(K);
tmcFreeLocalVar(S);
tmcFreeLocalVar(summa);
tmcFreeLocalVar(C);
tmcFreeLocalVar(B);
tmcFreeLocalVar(A);
tmcFreeLocalVar(x);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(16);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 61

// % Lines 62--62:
